import cerqueira from "/assets/images/cerqueira.jpg";
import farmaciabrito from "/assets/images/farmaciabrito.jpg";
import santafe from "/assets/images/santafe.jpg";
import stillus from "/assets/images/stillus.jpg";
import muse from "/assets/images/identidade-visual.jpg";
import envelopamento from "/assets/images/envelopamento.jpg";
import coberturas from "/assets/images/coberturas.jpg";
import impressao from "/assets/images/impressao.jpg";
import totens from "/assets/images/totens.jpg";
import fachada from "/assets/images/fachada.jpg";
import luminosos from "/assets/images/luminosos.jpg";
import alphaville from "/assets/images/alphaville.jpg";
import bragro from "/assets/images/bragro.jpg";
import jatoba from "/assets/images/jatoba.jpg";
import mundial from "/assets/images/mundial.jpg";
import brasilgas from "/assets/images/brasilgas.jpg";
import pirelli from "/assets/images/pirelli.jpg";
import construpiso from "/assets/images/construpiso.jpg";
import avesso from "/assets/images/avesso.jpg";
import pergolado from "/assets/images/pergolado.jpg";
import acai from "/assets/images/acai.jpg";
import leo from "/assets/images/leo.jpg";
import vox from "/assets/images/vox.jpg";
import chiquinho from "/assets/images/chiquinho.jpg";
import depoimentosbg from "/assets/images/depoimentosbg.jpg";
import voxCard from "/assets/images/voxCard.jpg";
import copCard from "/assets/images/copCard.jpg";
import casaCard from "/assets/images/casaCard.jpg";
import cerqueiraCard from "/assets/images/cerqueiraCard.jpg";
import msCard from "/assets/images/msCard.jpg";
import perereCard from "/assets/images/perereCard.jpg";

import logo from "/assets/images/logo.png";
import quem from "/assets/images/quem.png";
import zap from "/assets/images/zapLogo.png";
import barra from "/assets/images/barra.png";
import experiencia from "/assets/images/experiencia.png";
import projetos from "/assets/images/projetos.png";
import qualidade from "/assets/images/qualidade.png";
import equipe from "/assets/images/equipe.png";
import solucoes from "/assets/images/solucoes.png";
import alphavilleLogo from "/assets/images/alphaville.png";
import analiseLogo from "/assets/images/analise.png";
import autoglassLogo from "/assets/images/autoglass.png";
import bahiaLogo from "/assets/images/bahia.png";
import belasLogo from "/assets/images/belas.png";
import belvedreLogo from "/assets/images/belvedere.png";
import casaLogo from "/assets/images/casa.png";
import casteloLogo from "/assets/images/castelo.png";
import cerqueiraLogo from "/assets/images/cerqueira.png";
import clameveLogo from "/assets/images/clameve.png";
import cocaLogo from "/assets/images/coca.png";
import colegioLogo from "/assets/images/colegio.png";
import copLogo from "/assets/images/cop.png";
import draLogo from "/assets/images/dra.png";
import farmaciaLogo from "/assets/images/farmacia.png";
import fckLogo from "/assets/images/fck.png";
import gbarbosaLogo from "/assets/images/gbarbosa.png";
import gerdauLogo from "/assets/images/gerdau.png";
import indaiaLogo from "/assets/images/indaia.png";
import ladeLogo from "/assets/images/lade.png";
import leoLogo from "/assets/images/leo.png";
import maskateLogo from "/assets/images/maskate.png";
import mirasolLogo from "/assets/images/mirasol.png";
import mrpoloLogo from "/assets/images/mrpolo.png";
import mrvLogo from "/assets/images/mrv.png";
import msmenezesLogo from "/assets/images/msmenezes.png";
import nacionalLogo from "/assets/images/nacional.png";
import oficinaLogo from "/assets/images/oficina.png";
import oralLogo from "/assets/images/oral.png";
import perereLogo from "/assets/images/perere.png";
import sbLogo from "/assets/images/sb.png";

export const cerqueiraImg = cerqueira;
export const britoImg = farmaciabrito;
export const santafeImg = santafe;
export const stillusImg = stillus;
export const museImg = muse;
export const envelopamentoImg = envelopamento;
export const coberturasImg = coberturas;
export const impressaoImg = impressao;
export const totensImg = totens;
export const fachadaImg = fachada;
export const luminososImg = luminosos;
export const alphavilleImg = alphaville;
export const bragroImg = bragro;
export const jatobaImg = jatoba;
export const mundialImg = mundial;
export const brasilgasImg = brasilgas;
export const pirelliImg = pirelli;
export const construpisoImg = construpiso;
export const avessoImg = avesso;
export const pergoladoImg = pergolado;
export const acaiImg = acai;
export const leoImg = leo;
export const voxImg = vox;
export const chiquinhoImg = chiquinho;
export const depoimentosbgImg = depoimentosbg;
export const voxCardImg = voxCard;
export const copCardImg = copCard;
export const msCardImg = msCard;
export const perereCardImg = perereCard;
export const cerqueiraCardImg = cerqueiraCard;
export const casaCardImg = casaCard;

export const solucoesImg = solucoes;
export const equipeImg = equipe;
export const qualidadeImg = qualidade;
export const projetosImg = projetos;
export const experienciaImg = experiencia;
export const barraImg = barra;
export const zapImg = zap;
export const sobreImg = quem;
export const logoImg = logo;
export const alphavilleLogoImg = alphavilleLogo;
export const analiseLogoImg = analiseLogo;
export const autoglassLogoImg = autoglassLogo;
export const bahiaLogoImg = bahiaLogo;
export const belasLogoImg = belasLogo;
export const belvedreLogoImg = belvedreLogo;
export const casaLogoImg = casaLogo;
export const casteloLogoImg = casteloLogo;
export const cerqueiraLogoImg = cerqueiraLogo;
export const clameveLogoImg = clameveLogo;
export const cocaLogoImg = cocaLogo;
export const colegioLogoImg = colegioLogo;
export const copLogoImg = copLogo;
export const draLogoImg = draLogo;
export const farmaciaLogoImg = farmaciaLogo;
export const fckLogoImg = fckLogo;
export const gbarbosaLogoImg = gbarbosaLogo;
export const gerdauLogoImg = gerdauLogo;
export const indaiaLogoImg = indaiaLogo;
export const ladeLogoImg = ladeLogo;
export const leoLogoImg = leoLogo;
export const maskateLogoImg = maskateLogo;
export const mirasolLogoImg = mirasolLogo;
export const mrpoloLogoImg = mrpoloLogo;
export const mrvLogoImg = mrvLogo;
export const msmenezesLogoImg = msmenezesLogo;
export const nacionalLogoImg = nacionalLogo;
export const oficinaLogoImg = oficinaLogo;
export const oralLogoImg = oralLogo;
export const perereLogoImg = perereLogo;
export const sbLogoImg = sbLogo;
