import logo from "/assets/images/logo.png";
import cerqueira from "/assets/images/cerqueira.jpg";
import farmaciabrito from "/assets/images/farmaciabrito.jpg";
import santafe from "/assets/images/santafe.jpg";
import stillus from "/assets/images/stillus.jpg";
import quem from "/assets/images/quem.png";
import zap from "/assets/images/zapLogo.png";
import barra from "/assets/images/barra.png";
import experiencia from "/assets/images/experiencia.png";
import projetos from "/assets/images/projetos.png";
import qualidade from "/assets/images/qualidade.png";
import equipe from "/assets/images/equipe.png";
import solucoes from "/assets/images/solucoes.png";

export const logoImg = logo;
export const cerqueiraImg = cerqueira;
export const britoImg = farmaciabrito;
export const santafeImg = santafe;
export const stillusImg = stillus;
export const sobreImg = quem;
export const zapImg = zap;
export const barraImg = barra;
export const experienciaImg = experiencia;
export const projetosImg = projetos;
export const qualidadeImg = qualidade;
export const equipeImg = equipe;
export const solucoesImg = solucoes;
