import cerqueira from "/assets/images/cerqueira.jpg";
import farmaciabrito from "/assets/images/farmaciabrito.jpg";
import santafe from "/assets/images/santafe.jpg";
import stillus from "/assets/images/stillus.jpg";
import muse from "/assets/images/identidade-visual.jpg";
import envelopamento from "/assets/images/envelopamento.jpg";
import coberturas from "/assets/images/coberturas.jpg";
import impressao from "/assets/images/impressao.jpg";
import totens from "/assets/images/totens.jpg";
import fachada from "/assets/images/fachada.jpg";
import luminosos from "/assets/images/luminosos.jpg";
import alphaville from "/assets/images/alphaville.jpg";

import logo from "/assets/images/logo.png";
import quem from "/assets/images/quem.png";
import zap from "/assets/images/zapLogo.png";
import barra from "/assets/images/barra.png";
import experiencia from "/assets/images/experiencia.png";
import projetos from "/assets/images/projetos.png";
import qualidade from "/assets/images/qualidade.png";
import equipe from "/assets/images/equipe.png";
import solucoes from "/assets/images/solucoes.png";

export const cerqueiraImg = cerqueira;
export const britoImg = farmaciabrito;
export const santafeImg = santafe;
export const stillusImg = stillus;
export const museImg = muse;
export const envelopamentoImg = envelopamento;
export const coberturasImg = coberturas;
export const impressaoImg = impressao;
export const totensImg = totens;
export const fachadaImg = fachada;
export const luminososImg = luminosos;
export const alphavilleImg = alphaville;

export const solucoesImg = solucoes;
export const equipeImg = equipe;
export const qualidadeImg = qualidade;
export const projetosImg = projetos;
export const experienciaImg = experiencia;
export const barraImg = barra;
export const zapImg = zap;
export const sobreImg = quem;
export const logoImg = logo;
